### ISSUE TITLE
Write a description of the tiger mosquito algorithm and how it works

### ISSUE THREAD

**Issue by JJ** [sigevo-summer-school-2018/tiger-mosquito-algorithm#1]
A 2-3 paragraph description of the algorithm

**Comment by iljeodugu** [comment]
An algorithm that removes mosquitoes that carry dengue virus, zykova virus, yellow fever virus. You will choose a pheromone to eliminate mosquitoes, a good pheromone and a bad pheromone to make a pheromone that attracts tiger mosquitoes.

1. Initialize the pheromone.
2. Measure the fitness of pheromones.
3. Use the tormant selection to get the results.
4. Cross over each result to get a new generation.
5. repeat

**Comment by JJ** [comment]
Please write that [`README.md`](https://github.com/sigevo-summer-school-2018/tiger-mosquito-algorithm/blob/master/README.md) to write that.
