### ISSUE TITLE
Describe tournament selection algorithm

### ISSUE THREAD

**Issue by JJ** [sigevo-summer-school-2018/tiger-mosquito-algorithm#10]
Including the time-varying component used to stochastically select either pheromone or fitness.

**Comment by satuma777** [comment]
@JJ The proposed selection scheme is described before post. Please review the description.

**Comment by JJ** [comment]
It's OK but the typos, please check them. After adding it using an editor you can spell-check.

**Comment by satuma777** [comment]
modified typo

**Comment by satuma777** [comment]
@JJ Please review the modified description.

**Comment by JJ** [comment]
To the file, then :+1:
