### ISSUE TITLE
Start programming fitness functions

### ISSUE THREAD

**Issue by JJ** [sigevo-summer-school-2018/tiger-mosquito-algorithm#17]
onemax is probably done already, NK-landscape needs probably to be done in Python.
Since @satuma777 has used Python 3, I think we can use that all the way.

**Comment by iljeodugu** [comment]
[Fitness](https://github.com/sigevo-summer-school-2018/tiger-mosquito-algorithm/tree/master/code/Fitness%20function) upload.

**Comment by iljeodugu** [comment]
@tushar-semwal Can you give me a review? Thank you.

**Comment by hmonzon** [comment]
NK-landscape fitness functions works at it should so I'm closing this issue.
