### ISSUE TITLE
Find a place to have lunch meetings

### ISSUE THREAD

**Issue by JJ** [sigevo-summer-school-2018/tiger-mosquito-algorithm#18]
Site requirements:

- Time walking < 5 mins

- Food price < 1000Yen

- Wifi == True

- Available date == Tuesday or date == Wednesday

- Vegetarian options available.

**Comment by JJ** [comment]
@JJ Also site requirement available date == Tuesday or date == Wednesday

**Comment by JJ** [comment]
We can order pizza tomorrow too if you liked that. Maybe get the order at 12 so that we can have lunch by 12:30

**Comment by iljeodugu** [comment]
[KFC](https://www.google.com/maps/place/KFC/@34.9792512,135.7524448,19.04z/data=!4m5!3m4!1s0x600108aa7f502285:0x7f3b21bea130a1a7!8m2!3d34.9795998!4d135.7521363?hl=ko) - Wi-Fi enabled, takes about 7 minutes, maybe salad, As a last resort
[Ramen](https://www.google.com/maps/place/Ramen+Daiei/@34.9768382,135.756371,18z/data=!4m12!1m6!3m5!1s0x0:0x17ae2b3941a168dc!2sKyoto+Terrsa!8m2!3d34.9774691!4d135.7559531!3m4!1s0x60010f53e80a9541:0xeb7d8351d2862f3d!8m2!3d34.9759521!4d135.7580359?hl=ko) - Maybe Wifi, I do not know if it will be vegetable. 5 minutes away
[Family Restaurant](https://www.google.com/maps/place/Gusto+Kyoto+Jujo/@34.9740721,135.7547437,19.3z/data=!4m5!3m4!1s0x60010f5680aa8b53:0x8853b2e41b1bc6ce!8m2!3d34.9734323!4d135.7544839?hl=ko) - Wi-Fi enabled, takes about 7 minutes, maybe salad
I have found it hard. If there is a better way, please suggest.

**Comment by iljeodugu** [comment]
What does 'bring it to the hotel' mean?
