### ISSUE TITLE
State of the art

### ISSUE THREAD

**Issue by JJ** [sigevo-summer-school-2018/tiger-mosquito-algorithm#3]
Create a .bib file and a markdown file that makes an introduction to the state of the art.

**Comment by tushar-semwal** [comment]
Added three resources which inspired our algorithm. NO need to read the papers as they are purely from biology. Though you can quickly skim through the online source.
The file is here: tiger-mosquito-algorithm/survey.bib
Will be adding more to this file.
@JJ @hmonzon @satuma777 @christian-cl @iljeodugu

**Comment by JJ** [comment]
Great, thanks!

**Comment by tushar-semwal** [comment]
Should we close this issue? @JJ
